### ISSUE TITLE
NotoSansThaiUI-ttf phase III font's stacked diacritics seems more compressed than the NotoSansThaiUI-VH.ttf's ones

### ISSUE THREAD

**Issue by hrhatada** [notofonts/thai#2]
STEPS TO REPRODUCE

1. Download the NotoSansThaiUI-Regular.ttf font from https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-pipeline/unhinted/ttf/sans
2. Download the NotoSansThaiUI-VF.ttf font from https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-pipeline/unhinted/variable-ttf/sans
3. Use FontView tool, compare the following stacked diacritics "รั ภั ป็ ปิ วิ ซ็ ร์  ที่  ชื่ ซื้ ชื่ พื่ มื่ ขึ้ รื่ ริ่ นี้ อื่ ทั้ ตั้ ซ้ำ"

RESULT : NotoSansThaiUI-ttf phase III font's stacked diacritics seems more compressed than the NotoSansThaiUI-VH.ttf's ones. Please refer to the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/16353449/24275027/af3efd14-0fe9-11e7-9536-4c4e8101078c.png)

**Comment by simoncozens** [comment]
This appears to be fixed in the current statics:

![shape](https://github.com/notofonts/thai/assets/106728/a6aad906-c781-49c1-b87e-8f74abb59a68)

So I'm guessing it was a toolchain issue.
