### ISSUE TITLE
Tone mark not working

### ISSUE THREAD

**Issue by prawich-th** [notofonts/thai#24]
## Defect Report

> Noto fonts can be obtained from https://notofonts.github.io/
> If you find a problem with a released font, then please use this template to file a defect report.
> Before filing your report, please check if the issue has been fixed in the latest development build. You can get development builds by finding the font family on https://notofonts.github.io/ and following the link to "Development builds".

### Title 
  > Should be brief but contain essential information.
overlapped tone mark

### Font 
  > Full file name, for example 'NotoSansArmenian-Regular.ttf'.
  > You can upload the problem font here unless it is a Chinese, Japanese or Korean font (these are large).

### Where the font came from, and when

https://fonts.google.com/noto/specimen/Noto+Sans+Thai+Looped

### Font Version
Version 1.00

### OS name and version
Web & Ventura 

### Application name and version
All

### Issue
In t=Thai we have a tone mark that are stackable, in other fonts (including normal Noto sans Thai) the symbol will stack above of the previous character as shown below, In Noto Sans Thai Looped it just stack on top of each other.
<img width="830" alt="Screenshot 2566-04-04 at 11 31 45" src="https://user-images.githubusercontent.com/90727258/229687564-6e2d50a7-c5d4-4826-860c-268ecce16b96.png">

### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.
<img width="958" alt="Screenshot 2566-04-04 at 11 34 28" src="https://user-images.githubusercontent.com/90727258/229687904-f9183510-d66c-4799-a1b2-598e5128f627.png">

### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by simoncozens** [comment]
This does stack correctly in the latest Thai Looped release:

![shape](https://user-images.githubusercontent.com/106728/229723873-d2db292a-b0ff-4264-9876-bffac2bffd83.png)

Something is wrong with the version on Google Fonts; I'll take a look.

**Comment by prawich-th** [comment]
I tried the version on the noto font site and it works properly. Only google font version have a problem

**Comment by simoncozens** [comment]
It's fixed on Google Fonts now.
<img width="128" alt="Screenshot 2023-07-10 at 13 08 43" src="https://github.com/notofonts/thai/assets/106728/5952ab18-02b7-4467-8399-66972ac8ed80">
